### ISSUE TITLE
Release a new version 0.1.1

### ISSUE THREAD

**Issue by droodle** [dailymotion/dailymotion-sdk-python#12]
Hi,

could you release a new version (like 0.1.1) on PyPI containing the recent bugfixes for the session storage. That would make our packaging and installation steps easier.

Thanks

**Comment by Amzani** [comment]
Hello @droodle,

Yeah i will update it soon after testing the new "dev" branch.
https://github.com/dailymotion/dailymotion-sdk-python/pull/11

Thanks

**Comment by Amzani** [comment]
Updated
