### ISSUE TITLE
Getting error "NameError: name 'API_KEY' is not defined"

### ISSUE THREAD

**Issue by ahmadwalid231** [dailymotion/dailymotion-sdk-python#20]
I don't know, what am I doing wrong. I have configured the API_KEY, SECRET_KEY etc. in the config.py file, still getting this error. Seems like config file is not read at all, though I have also used import config. 
I'm just testing out simple authenticated call.

**Comment by Amzani** [comment]
Hello @ahmadwalid231 
Can you copy past you code ?  
thanks

**Comment by MathildeS** [comment]
@ahmadwalid231 we need your code so we can help on this issue, otherwise we'll have to close it. 

There should be no problem if you import the config file properly, so you need to check it is righlty formatted and that it is in a place where you script can read it.

**Comment by xxKoBrAx** [comment]
NameError: name 'google_api_key' is not defined can anyone help me to fix it?? tool is phonia on kali linux
