### ISSUE TITLE
incorrect process unicode filename

### ISSUE THREAD

**Issue by AndCycle** [dailymotion/dailymotion-sdk-python#23]
064ad1e is not a correct fix as it will break under python 2, 
trigger https://github.com/kennethreitz/requests/issues/2639

**Comment by AndCycle** [comment]
remove that quick fix will hit another issue

dailymotion.DailymotionUploadError: missing file

http://stackoverflow.com/questions/23741585/dailymotion-upload-api-missing-file-error
which probably deep down in requests or urllib3 module

this dirty fix is pass a dummy filename if title have been specific when upload,

m = MultipartEncoder(fields={'file': ('dummy.%s'%os.path.splitext(file_path)[1], open(file_path, 'rb'))})

**Comment by tsunammis** [comment]
Hello,

Sorry for the delay, we rollbacked the commit that break Python 2 compatibility. Furthermore, as [the patch on urllib3](https://github.com/shazow/urllib3/pull/818) has been[ integrated to requests](https://github.com/kennethreitz/requests/commit/f69d8c16ed47fa87b2cd0e7b8ad4ecf4871cb5c1), the bug should be not be present anymore.

Let me know if it is not the case.

Have a good day.

**Comment by AndCycle** [comment]
still got the missing file error over requests=2.10.0,
really nasty issue.

Python 2.7.10
upload file that filename have japanese in it under linux

**Comment by tsunammis** [comment]
Hello @AndCycle 

We identified the use-case where the SDK doesn't work. We are working on it.

Regards,

**Comment by AndCycle** [comment]
@tsunammis woops, that's fast, I am fine with my workaround so no rush here :p

**Comment by tsunammis** [comment]
@AndCycle How do you handle this case currently ? I'm curious :)

**Comment by AndCycle** [comment]
@tsunammis the dummy filename solution mentioned earlier

dailymotion.py

```
-        m = MultipartEncoder(fields={'file': (os.path.basename(file_path), open(file_path, 'rb'))})
+        m = MultipartEncoder(fields={'file': (u'dummy.%s'%os.path.splitext(file_path)[1], open(file_path, 'rb'))})
```

**Comment by tsunammis** [comment]
@AndCycle the issue regarding unicode chars should be fixed, could you try ?

**Comment by AndCycle** [comment]
@tsunammis sorry for the late reply, this fix is confirmed.

**Comment by tsunammis** [comment]
@AndCycle Great :)
