### ISSUE TITLE
[Feature request]Make calls with existing access token

### ISSUE THREAD

**Issue by ghost** [dailymotion/dailymotion-sdk-python#24]
Hello,

It would be nice if the SDK could use an existing access token, that is otherwise acquired, when making requests. The facebook and twitter SDKs allow this already, most likely the google/youtube SDKs as well.

Maybe something like

``` python
d = dailymotion.Dailymotion()
d.set_grant_type(grant_type='access_token', access_token='access token here')
user = d.get('/user/heyId')
```

Cheers

**Comment by yaziine** [comment]
Hi ! 

Thanks for the heads-up, we'll have a look into this feature.

Best

**Comment by Amzani** [comment]
Hello @LoveIsGrief ,
Could you explain your use case ? and why you need to set an existing access token ?

Thanks.

**Comment by ghost** [comment]
Hi @Amzani 

The usecase is:
1. Get API token through other means (generalized procedure to support other OAuth services) and store it in DB
2. Initiate SDK with stored API token
3. Make calls

Facebook, twitter and youtube allow this and with a few modifications it should be possible to do so with dailymotion as well.

Cheers.

**Comment by Amzani** [comment]
Thanks @LoveIsGrief ,

Of course it's possible, i just wanted to understand the use case.
How you will handle refreshing access tokens ?

**Comment by Amzani** [comment]
Fixed in https://github.com/dailymotion/dailymotion-sdk-python/pull/26

**Comment by ghost** [comment]
I never responded to you @Amzani , sorry. But it seems like this was handled in the PR :+1: 

Thanks!
