### ISSUE TITLE
PyPi classifiers info is empty

### ISSUE THREAD

**Issue by rednaks** [dailymotion/dailymotion-sdk-python#29]
Hello, 
I'm using a tool `caniusepython3` to check if my project's dependencies are compatible with python3 or not, and this tool is using pypi classifiers to check. basically it's checking if 
`"Programming Language :: Python :: 3"` is in the classifiers list.
So the tool reported that `dailymotion` is not compatible with python3 but the reason is just that the list of classifiers [1] is empty.
So 
1. Can you add `"Programming Language :: Python :: 3"` in setup.py https://github.com/dailymotion/dailymotion-sdk-python/blob/master/setup.py#L9   ?  since the python3 linter was satisfied with the code.
2. Make sure the Classifiers in PyPi are updated as well.

It will really help gaining a lot of time to those trying to migrate :) 
Thank you :) 

[1] https://pypi.org/pypi/dailymotion/json

**Comment by nicoferron** [comment]
Hello @rednaks Thank you for your feedback.
We will do the modification in order to be detected as python3 compatible.

Regards,

**Comment by nicoferron** [comment]
Hello @rednaks,

Classifiers are updated. 
Thank you again for helping us improve our product.

Regards,
