### ISSUE TITLE
Undeclared variables

### ISSUE THREAD

**Issue by fevral13** [dailymotion/dailymotion-sdk-python#3]
There are undeclared variables at lines:
https://github.com/dailymotion/dailymotion-sdk-python/blob/master/dailymotion.py#L179
https://github.com/dailymotion/dailymotion-sdk-python/blob/master/dailymotion.py#L185
https://github.com/dailymotion/dailymotion-sdk-python/blob/master/dailymotion.py#L240

They are in except blocks and eventually will throw unexpected exception

**Comment by OpenHaus** [comment]
Those issues cause trouble using the SDK with Python3. Would be nice if it could be fixed anytime soon. I am planning on using the SDK for a Hack4Europe project.

**Comment by Amzani** [comment]
Fixed.
Thanks.
