### ISSUE TITLE
AttributeError: module 'dailymotion' has no attribute 'Dailymotion'

### ISSUE THREAD

**Issue by Nex4rius** [dailymotion/dailymotion-sdk-python#35]
I'm trying out the public API call example:

```python
d = dailymotion.Dailymotion()
d.get('/videos')
```

I've created my file with:
```python
import dailymotion

d = dailymotion.Dailymotion() # <- it fails here already
print(d.get('/videos'))
```

and I'm getting the error
```
AttributeError: module 'dailymotion' has no attribute 'Dailymotion'
```
What am I doing wrong?
Any help would be much appreciated thanks ;)

Edit I've just installed it via pip and I have version 0.2.5.

**Comment by nicoferron** [comment]
Hello @Nex4rius, 
Which version of PIP and Python are you using? What the result of these two commands?
pip -V; python -V

In your script, is `dailymotion.__version__` returning '0.2.5'?
What's the result of `dir(dailymotion)`?

This information could help us to find the issue

Regards

**Comment by Nex4rius** [comment]
Thanks for the response:

I have:
pip: 20.2.3
python 3.7.4

```python
dailymotion.__version__
```
is returning:
```python
AttributeError: module 'dailymotion' has no attribute '__version__'
```
And this:
```python
dir(dailymotion)
```
is returning:
```python
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'dailymotion']
```
I've also run
```cmd
pip uninstall dailymotion -y
pip install dailymotion
```
and tried everything again but I got the same result.

**Comment by nicoferron** [comment]
Your import isn't referencing the dailymotion sdk. 
You should check the value of `dailymotion.__file__` to get the file it's referencing.
Have you created a module named dailymotion.py in your project? I suppose there is a conflict in the naming

**Comment by Nex4rius** [comment]
You are absolutely correct thanks ;)
