### ISSUE TITLE
Remove pycurl dependency, keep only requests

### ISSUE THREAD

**Issue by droodle** [dailymotion/dailymotion-sdk-python#6]
Hi,

it would be great to remove the pycurl dependency or at least let me choose which network library to use.

Some time ago, I ran into trouble when trying to install curl libraries on an old system but I had no problem installing requests.

requests is listed in the project dependencies but there are part of the code not implemented for this lib.

Cheers

**Comment by Amzani** [comment]
Requests is good library, but when i wrote this code, it was too slow to upload large files.

I think there is some improvements to test with streaming uploads (http://docs.python-requests.org/en/latest/user/advanced/#streaming-uploads).

I will bench it for the next release.
You are welcome to pull-request :)

Thx
