### ISSUE TITLE
The nosetests -v shows an error that .db does not exist

### ISSUE THREAD

**Issue by mox386** [dailymotion/dailymotion-sdk-python#9]
All of the tests result in this file not existing
/home/<user>/.dailymotion_sdk_session_<username>.db

However, the file does exist without the .db ad the end. As a workaround simply rename the files with a .db at the end, and run the test again.

cd ~
mv .dailymotion_sdk_session_default .dailymotion_sdk_session_default.db

and the same for the user session

**Comment by Amzani** [comment]
Fixed.
